apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/devops-cc-472518/campusconnect-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "development"
        - name: JWT_SECRET
          value: "your-secret-key"  # In production, use kubernetes secrets
        - name: CORS_ORIGIN
          value: "http://localhost:30000"
        - name: PORT
          value: "5000"
        - name: HOST
          value: "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001
